### Get History Order (USDT-FUTURES) demo
< {%
  import {gen_sign} from 'sign.js'
  gen_sign(request);
%}
GET {{api_host}}/api/v2/mix/order/orders-history?productType=USDT-FUTURES&symbol=BTCUSDT
ACCESS-KEY: {{api_key}}
ACCESS-SIGN: {{sign}}
ACCESS-TIMESTAMP: {{timestamp}}
ACCESS-PASSPHRASE: {{api_passphrase}}
paptrading: 1

### Get Pending Orders (USDT-FUTURES) demo
< {%
  import {gen_sign} from 'sign.js'
  gen_sign(request);
%}
GET {{api_host}}/api/v2/mix/order/orders-pending?productType=USDT-FUTURES
ACCESS-KEY: {{api_key}}
ACCESS-SIGN: {{sign}}
ACCESS-TIMESTAMP: {{timestamp}}
ACCESS-PASSPHRASE: {{api_passphrase}}
paptrading: 1

### Get Order Fills (USDT-FUTURES) demo
< {%
  import {gen_sign} from 'sign.js'
  gen_sign(request);
%}
GET {{api_host}}/api/v2/mix/order/fills?productType=USDT-FUTURES
ACCESS-KEY: {{api_key}}
ACCESS-SIGN: {{sign}}
ACCESS-TIMESTAMP: {{timestamp}}
ACCESS-PASSPHRASE: {{api_passphrase}}
paptrading: 1

### Place market order USDT-FUTURES, BTCUSDT
< {%
  import {gen_sign} from 'sign.js'
  gen_sign(request);
%}
POST {{api_host}}/api/v2/mix/order/place-order
ACCESS-KEY: {{api_key}}
ACCESS-SIGN: {{sign}}
ACCESS-TIMESTAMP: {{timestamp}}
ACCESS-PASSPHRASE: {{api_passphrase}}
Content-Type: application/json
paptrading: 1

{
  "productType": "USDT-FUTURES",
  "symbol": "BTCUSDT",
  "marginCoin": "USDT",
  "marginMode": "isolated",
  "side" : "buy",
  "orderType": "market",
  "size": "0.001",
  "clientOid": "b9f0c8a1-52c4-4cb2-8d2a-5f8df95f9c3e"
}

### Place position stop loss USDT-FUTURES, BTCUSDT
< {%
  import {gen_sign} from 'sign.js'
  gen_sign(request);
%}
POST {{api_host}}/api/v2/mix/order/place-tpsl-order
ACCESS-KEY: {{api_key}}
ACCESS-SIGN: {{sign}}
ACCESS-TIMESTAMP: {{timestamp}}
ACCESS-PASSPHRASE: {{api_passphrase}}
Content-Type: application/json
paptrading: 1

{
  "productType": "USDT-FUTURES",
  "symbol": "BTCUSDT",
  "marginCoin": "USDT",
  "planType": "loss_plan",
  "triggerPrice": "90000",
  "triggerType": "mark_price",
  "holdSide": "buy",
  "size": "0.001"
}

### Cancel position stop loss USDT-FUTURES, BTCUSDT
< {%
  import {gen_sign} from 'sign.js'
  gen_sign(request);
%}
POST {{api_host}}/api/v2/mix/order/cancel-plan-order
ACCESS-KEY: {{api_key}}
ACCESS-SIGN: {{sign}}
ACCESS-TIMESTAMP: {{timestamp}}
ACCESS-PASSPHRASE: {{api_passphrase}}
Content-Type: application/json
paptrading: 1

{
  "productType": "USDT-FUTURES",
  "symbol": "BTCUSDT",
  "marginCoin": "USDT",
  "planType": "loss_plan"
}

### Cancel all orders for USDT-FUTURES
< {%
  import {gen_sign} from 'sign.js'
  gen_sign(request);
%}
POST {{api_host}}/api/v2/mix/order/cancel-all-orders
ACCESS-KEY: {{api_key}}
ACCESS-SIGN: {{sign}}
ACCESS-TIMESTAMP: {{timestamp}}
ACCESS-PASSPHRASE: {{api_passphrase}}
Content-Type: application/json
paptrading: 1

{
  "productType": "USDT-FUTURES",
  "marginCoin": "USDT"
}

### Flash close positions for USDT-FUTURES
< {%
  import {gen_sign} from 'sign.js'
  gen_sign(request);
%}
POST {{api_host}}/api/v2/mix/order/close-positions
ACCESS-KEY: {{api_key}}
ACCESS-SIGN: {{sign}}
ACCESS-TIMESTAMP: {{timestamp}}
ACCESS-PASSPHRASE: {{api_passphrase}}
Content-Type: application/json
paptrading: 1

{
  "productType": "USDT-FUTURES"
}