### Get History Order (USDT-FUTURES) demo
< {%
  import {gen_sign} from 'sign.js'
  gen_sign(request);
%}
GET {{api_host}}/api/v2/mix/order/orders-history?productType=USDT-FUTURES&symbol=BTCUSDT
ACCESS-KEY: {{api_key}}
ACCESS-SIGN: {{sign}}
ACCESS-TIMESTAMP: {{timestamp}}
ACCESS-PASSPHRASE: {{api_passphrase}}
paptrading: 1