package org.knowm.xchange.bitgetfutures.dto.trade;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.math.BigDecimal;
import java.time.Instant;
import lombok.Builder;
import lombok.Data;
import lombok.extern.jackson.Jacksonized;
import org.knowm.xchange.bitgetfutures.config.converter.StringToBooleanConverter;
import org.knowm.xchange.bitgetfutures.config.converter.StringToCurrencyConverter;
import org.knowm.xchange.bitgetfutures.config.converter.StringToOrderTypeConverter;
import org.knowm.xchange.currency.Currency;
import org.knowm.xchange.dto.Order;

@Data
@Builder
@Jacksonized
public class BitgetFuturesOrderDetailDto {

  /**
   * Trading pair
   */
  @JsonProperty("symbol")
  private String symbol;

  /**
   * Amount
   */
  @JsonProperty("size")
  private BigDecimal size;

  /**
   * Order ID
   */
  @JsonProperty("orderId")
  private String orderId;

  /**
   * Customize order ID
   */
  @JsonProperty("clientOid")
  private String clientOid;

  /**
   * Amount of coins traded
   */
  @JsonProperty("baseVolume")
  private BigDecimal baseVolume;

  /**
   * Transaction fee
   */
  @JsonProperty("fee")
  private BigDecimal fee;

  /**
   * Order price
   */
  @JsonProperty("price")
  private BigDecimal price;

  /**
   * Average price
   */
  @JsonProperty("priceAvg")
  private BigDecimal priceAvg;
  /**
   * Order status
   */
  @JsonProperty("status")
  private BitgetFuturesOrderStatus status;

  /**
   * Direction (buy or sell)
   */
  @JsonProperty("side")
  @JsonDeserialize(converter = StringToOrderTypeConverter.class)
  private Order.OrderType orderSide;

  /**
   * Order expiration date
   */
  @JsonProperty("force")
  private BitgetFuturesOrderTimeInForce timeInForce;

  /**
   * Total PnL
   */
  @JsonProperty("totalProfits")
  private BigDecimal profit;

  /**
   * Position direction
   */
  @JsonProperty("posSide")
  private BitgetFuturesOrderPositionSide positionSide;

  /**
   * Margin coin
   */
  @JsonProperty("marginCoin")
  @JsonDeserialize(converter = StringToCurrencyConverter.class)
  private Currency marginCurrency;

  /**
   * Trading amount in quoting coin
   */
  @JsonProperty("quoteVolume")
  private BigDecimal quoteVolume;

  /**
   * Leverage
   */
  @JsonProperty("leverage")
  private BigDecimal leverage;

  /**
   * Margin mode
   */
  @JsonProperty("marginMode")
  private BitgetFuturesMarginMode marginMode;

  /**
   * Whether or not to just reduce the position.
   */
  @JsonProperty("reduceOnly")
  @JsonDeserialize(converter = StringToBooleanConverter.class)
  private Boolean reduceOnly;

  /**
   * Order source WEB: Orders created on the website API: Orders created on API SYS: System managed
   * orders, usually generated by forced liquidation logic ANDROID: Orders created on the Android
   * app IOS: Orders created on the iOS app
   */
  @JsonProperty("enterPointSource")
  private String enterPointSource;

  /**
   * Direction
   * TODO See if we need to map with an Enum
   * close: Close (open and close mode)
   * open: Open (open and close mode)
   * reduce_close_long: Liquidate partial long positions for hedge position mode
   * reduce_close_short：Liquidate partial short positions for hedge position mode
   * burst_close_long：Liquidate long positions for hedge position mode
   * burst_close_short：Liquidate short positions for hedge position mode
   * offset_close_long：Liquidate partial long positions for netting for hedge position mode
   * offset_close_short：Liquidate partial short positions for netting for hedge position mode
   * delivery_close_long：Delivery long positions for hedge position mode
   * delivery_close_short：Delivery short positions for hedge position mode
   * dte_sys_adl_close_long：ADL close long position for hedge position mode
   * dte_sys_adl_close_short：ADL close short position for hedge position mode
   * buy_single：Buy, one way postion mode
   * sell_single：Sell, one way postion mode
   * reduce_buy_single：Liquidate partial positions, buy, one way position mode
   * reduce_sell_single：Liquidate partial positions, sell, one way position mode
   * burst_buy_single：Liquidate short positions, buy, one way postion mode
   * burst_sell_single：Liquidate partial positions, sell, one way position mode
   * delivery_sell_single：Delivery sell, one way position mode
   * delivery_buy_single：Delivery buy, one way position mode
   * dte_sys_adl_buy_in_single_side_mode：ADL close position, buy, one way position mode
   * dte_sys_adl_sell_in_single_side_mode：ADL close position, sell, one way position mode
   */
  @JsonProperty("tradeSide")
  private String tradeSide;

  /**
   * Position mode
   */
  @JsonProperty("posMode")
  private BitgetFuturesPositionMode positionMode;

  /**
   * Order type
   */
  @JsonProperty("orderType")
  private BitgetFuturesOrderType orderType;

  /**
   * Order source normal: Normal order market: market order profit_market: Market TP order
   * loss_market: Market SL order Trader_delegate: Elite trade order trader_profit: Trader takes
   * profit trader_loss: Trader stops loss reverse: Reversed orders trader_reverse: Reversed elite
   * trades profit_limit: Take-profit limit order loss_limit: Stop-loss limit order liquidation:
   * Liquidation order delivery_close_long: close long positions delivery_close_short: close short
   * positions pos_profit_limit: Position take-profit limit order pos_profit_market: Position
   * take-profit market order pos_loss_limit: Position stop-loss limit order pos_loss_market:
   * Position stop-loss market order profit_chase: Take Profit Chase Order loss_chase: Stop Loss
   * Chase Order follower_delegate: Follower Delegate Order reduce_offset: Reduce Position Offset
   * Order market_risk: Best Price Risk Handling plan_limit: Limit Plan Order plan_market: Best
   * Price Plan Order pos_loss_limit: Position Stop Loss Limit strategy_positive: Strategy-Positive
   * Grid strategy_reverse: Strategy-Reverse Grid strategy_unlimited: Unlimited Strategy move_limit:
   * Limit Moving Take Profit and Stop Loss move_market: Best Price Moving Take Profit and Stop Loss
   * tracking_limit: Limit Trailing Order tracking_market: Best Price Trailing Order
   * strategy_dca_positive: DCA Strategy-Positive strategy_dca_reverse: DCA Strategy-Reverse
   * strategy_oco_limit: Strategy-OCO Limit Order strategy_oco_trigger: Strategy-OCO Trigger Order
   * modify_order_limit: Limit Modify Order strategy_regular_buy: Strategy-Regular Buy
   * strategy_grid_middle: Strategy-Neutral Grid
   */
  @JsonProperty("orderSource")
  private String orderSource;

  /**
   * Cancel reason
   */
  @JsonProperty("cancelReason")
  private BitgetFuturesOrderCancelReason cancelReason;
  /**
   * Creation time, ms
   */
  @JsonProperty("cTime")
  private Instant createdAt;
  /**
   * Update time, ms
   */
  @JsonProperty("uTime")
  private Instant updatedAt;

  /**
   * Set TP
   */
  @JsonProperty("presetStopSurplusPrice")
  private BigDecimal presetStopSurplusPrice;

  /**
   * Set SL
   */
  @JsonProperty("presetStopLossPrice")
  private BigDecimal presetStopLossPrice;

  /**
   * Preset Take Profit Trigger type
   */
  @JsonProperty("presetStopSurplusType")
  private BitgetFuturesOrderPresetTriggerPriceType presetStopSurplusTriggerType;

  /**
   * Preset Take Profit Execution price
   */
  @JsonProperty("presetStopSurplusExecutePrice")
  private BigDecimal presetStopSurplusExecutePrice;

  /**
   * Preset Stop Loss Trigger type
   */
  @JsonProperty("presetStopLossType")
  private BitgetFuturesOrderPresetTriggerPriceType presetStopLossTriggerType;

  /**
   * Preset Stop Loss Execution price
   */
  @JsonProperty("presetStopLossExecutePrice")
  private BigDecimal presetStopLossExecutePrice;
}
