package org.knowm.xchange.bitgetfutures.dto.trade;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import lombok.Builder;
import lombok.Data;
import lombok.extern.jackson.Jacksonized;
import org.knowm.xchange.bitgetfutures.config.converter.StringToBooleanConverter;
import org.knowm.xchange.bitgetfutures.config.converter.StringToCurrencyConverter;
import org.knowm.xchange.bitgetfutures.config.converter.StringToOrderTypeConverter;
import org.knowm.xchange.currency.Currency;
import org.knowm.xchange.dto.Order;

@Data
@Builder
@Jacksonized
public class BitgetFuturesFillDto {

  /**
   * Transaction details
   */
  @JsonProperty("fillList")
  List<FillEntry> fillList;

  /**
   * The final Transaction ID. This is used when idLessThan/idGreaterThan is set as a range.
   */
  @JsonProperty("endId")
  private String endId;

  @Data
  @Builder
  @Jacksonized
  @JsonFormat(shape = JsonFormat.Shape.ARRAY)
  public static class FillEntry {

    /**
     * Transaction id
     */
    @JsonProperty("tradeId")
    private String tradeId;

    /**
     * Trading pair
     */
    @JsonProperty("symbol")
    private String symbol;

    /**
     * Order no.
     */
    @JsonProperty("orderId")
    private String orderId;

    /**
     * Order price
     */
    @JsonProperty("price")
    private BigDecimal price;

    /**
     * Amount of coins traded
     */
    @JsonProperty("baseVolume")
    private BigDecimal baseVolume;

    /**
     * Transaction fee
     */
    @JsonProperty("feeDetail")
    private FeeDetail feeDetail;

    /**
     * Type of transaction buy: Buy sell: Sell
     */
    @JsonProperty("side")
    @JsonDeserialize(converter = StringToOrderTypeConverter.class)
    private Order.OrderType orderSide;

    /**
     * Trading amount in quote currency
     */
    @JsonProperty("quoteVolume")
    private BigDecimal quoteVolume;

    /**
     * Profit
     */
    @JsonProperty("profit")
    private BigDecimal profit;

    /**
     * Order source WEB: Orders created on the website API: Orders created on API SYS: System
     * managed orders, usually generated by forced liquidation logic ANDROID: Orders created on the
     * Android app IOS: Orders created on the iOS app
     */
    @JsonProperty("enterPointSource")
    private String enterPointSource;

    /**
     * Direction close: Close (open and close mode) open: Open (open and close mode)
     * reduce_close_long: Liquidate partial long positions for hedge position mode
     * reduce_close_short：Liquidate partial short positions for hedge position mode
     * burst_close_long：Liquidate long positions for hedge position mode burst_close_short：Liquidate
     * short positions for hedge position mode offset_close_long：Liquidate partial long positions
     * for netting for hedge position mode offset_close_short：Liquidate partial short positions for
     * netting for hedge position mode delivery_close_long：Delivery long positions for hedge
     * position mode delivery_close_short：Delivery short positions for hedge position mode
     * dte_sys_adl_close_long：ADL close long position for hedge position mode
     * dte_sys_adl_close_short：ADL close short position for hedge position mode buy_single：Buy, one
     * way postion mode sell_single：Sell, one way postion mode reduce_buy_single：Liquidate partial
     * positions, buy, one way position mode reduce_sell_single：Liquidate partial positions, sell,
     * one way position mode burst_buy_single：Liquidate short positions, buy, one way postion mode
     * burst_sell_single：Liquidate partial positions, sell, one way position mode
     * delivery_sell_single：Delivery sell, one way position mode delivery_buy_single：Delivery buy,
     * one way position mode dte_sys_adl_buy_in_single_side_mode：ADL close position, buy, one way
     * position mode dte_sys_adl_sell_in_single_side_mode：ADL close position, sell, one way position
     * mode
     */
    @JsonProperty("tradeSide")
    private String tradeSide;

    /**
     * Position mode
     */
    @JsonProperty("posMode")
    private PositionMode positionMode;

    /**
     * Trader tag taker: Taker maker: Maker
     */
    @JsonProperty("tradeScope")
    private TradeScope tradeScope;

    /**
     * Date of transaction endId String The final order ID. This is used when
     * idLessThan/idGreaterThan is set as a range.
     */
    @JsonProperty("cTime")
    private Instant createdAt;

  }

  public enum PositionMode {
    @JsonProperty("one_way_mode")
    ONE_WAY_POSITION,
    @JsonProperty("hedge_mode")
    TWO_WAY_POSITION
  }

  public enum TradeScope {
    @JsonProperty("taker")
    TAKER,

    @JsonProperty("maker")
    MAKER
  }

  @Data
  @Builder
  @Jacksonized
  public static class FeeDetail {

    /**
     * Whether or not to deduct (vouchers)
     */
    @JsonProperty("deduction")
    @JsonDeserialize(converter = StringToBooleanConverter.class)
    private Boolean deduction;

    /**
     * Crypto ticker
     */
    @JsonProperty("feeCoin")
    @JsonDeserialize(converter = StringToCurrencyConverter.class)
    private Currency currency;

    /**
     * Total transaction fee discount
     */
    @JsonProperty("totalDeductionFee")
    private BigDecimal totalDeductionFee;

    /**
     * Total transaction fee
     */
    @JsonProperty("totalFee")
    private BigDecimal totalFee;
  }
}
